apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: "2020-07-10T18:58:25Z"
  generation: 1
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "2790940"
  selfLink: /apis/apps/v1/namespaces/default/deployments/web
  uid: 8dd08d8e-363d-4c86-8c5a-b9fd26c9605a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
